/******************************************************
*           DSA Lab Test 2: Problem 1 (driver.c)
*   
*              Do not edit this file.
* ****************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <sys/time.h>
#include <stdbool.h>
#include "tree.h"

void printList(unsigned int *list, unsigned int len)
{
    int i;
    for (i = 0; i < len; i++)
        printf("%u\t", list[i]);
    printf("\n");
}

void printTreeInorder(tree root)
{
    if(root != NULL)
    {
        printTreeInorder(root->left);
        printf("%u\t", root->data);
        printTreeInorder(root->right);
    }
}

int main(int argc, char *argv[])
{
    unsigned int p;
    int seed, size;
    
    scanf("%d %d", &seed, &p);
    srand(seed);
    
    // part A
    unsigned int *list = createList(p);
    printList(list, p);

    // part B
    tree root = constructTree(list, p);
    printTreeInorder(root);

    // part C
    bool status = matchTreeIterative(root, list, p);
    (status)? printf("\nCORRECT\n"): printf("\nWRONG\n");

    return 0;
}
